<?php
class Meanbee_Barcodes_Model_Config_Source_AnnotatorBarcodeSymbology
{
    public function toOptionArray() {
        $helper = Mage::helper('meanbee_barcodes');
        return array(
            array('value' => null,                              'label' => $helper->__('None')),
            array('value' => 'auspost',                         'label' => $helper->__('AusPost 4 State Customer Code')),
            array('value' => 'azteccode',                       'label' => $helper->__('Aztec Code')),
            array('value' => 'azteccodecompact',                'label' => $helper->__('Compact Aztec Code')),
            array('value' => 'aztecrune',                       'label' => $helper->__('Aztec Runes')),
            array('value' => 'bc412',                           'label' => $helper->__('BC412')),
            array('value' => 'channelcode',                     'label' => $helper->__('Channel Code')),
            array('value' => 'codablockf',                      'label' => $helper->__('Codablock F')),
            array('value' => 'code11',                          'label' => $helper->__('Code 11')),
            array('value' => 'code128',                         'label' => $helper->__('Code 128')),
            array('value' => 'code16k',                         'label' => $helper->__('Code 16K')),
            array('value' => 'code2of5',                        'label' => $helper->__('Code 25')),
            array('value' => 'code32',                          'label' => $helper->__('Italian Pharmacode')),
            array('value' => 'code39',                          'label' => $helper->__('Code 39')),
            array('value' => 'code39ext',                       'label' => $helper->__('Code 39 Extended')),
            array('value' => 'code49',                          'label' => $helper->__('Code 49')),
            array('value' => 'code93',                          'label' => $helper->__('Code 93')),
            array('value' => 'code93ext',                       'label' => $helper->__('Code 93 Extended')),
            array('value' => 'codeone',                         'label' => $helper->__('Code One')),
            array('value' => 'coop2of5',                        'label' => $helper->__('COOP 2 of 5')),
            array('value' => 'daft',                            'label' => $helper->__('Custom 4 state symbology')),
            array('value' => 'databarexpanded',                 'label' => $helper->__('GS1 DataBar Expanded')),
            array('value' => 'databarexpandedcomposite',        'label' => $helper->__('GS1 DataBar Expanded Composite')),
            array('value' => 'databarexpandedstacked',          'label' => $helper->__('GS1 DataBar Expanded Stacked')),
            array('value' => 'databarexpandedstackedcomposite', 'label' => $helper->__('GS1 DataBar Expanded Stacked Composite')),
            array('value' => 'databarlimited',                  'label' => $helper->__('GS1 DataBar Limited')),
            array('value' => 'databarlimitedcomposite',         'label' => $helper->__('GS1 DataBar Limited Composite')),
            array('value' => 'databaromni',                     'label' => $helper->__('GS1 DataBar Omnidirectional')),
            array('value' => 'databaromnicomposite',            'label' => $helper->__('GS1 DataBar Omnidirectional Composite')),
            array('value' => 'databarstacked',                  'label' => $helper->__('GS1 DataBar Stacked')),
            array('value' => 'databarstackedcomposite',         'label' => $helper->__('GS1 DataBar Stacked Composite')),
            array('value' => 'databarstackedomni',              'label' => $helper->__('GS1 DataBar Stacked Omnidirectional')),
            array('value' => 'databarstackedomnicomposite',     'label' => $helper->__('GS1 DataBar Stacked Omnidirectional Composite')),
            array('value' => 'databartruncated',                'label' => $helper->__('GS1 DataBar Truncated')),
            array('value' => 'databartruncatedcomposite',       'label' => $helper->__('GS1 DataBar Truncated Composite')),
            array('value' => 'datalogic2of5',                   'label' => $helper->__('Datalogic 2 of 5')),
            array('value' => 'datamatrix',                      'label' => $helper->__('Data Matrix')),
            array('value' => 'ean13',                           'label' => $helper->__('EAN-13')),
            array('value' => 'ean13composite',                  'label' => $helper->__('EAN-13 Composite')),
            array('value' => 'ean14',                           'label' => $helper->__('GS1-14')),
            array('value' => 'ean2',                            'label' => $helper->__('EAN-2 (2 digit addon)')),
            array('value' => 'ean5',                            'label' => $helper->__('EAN-5 (5 digit addon)')),
            array('value' => 'ean8',                            'label' => $helper->__('EAN-8')),
            array('value' => 'ean8composite',                   'label' => $helper->__('EAN-8 Composite')),
            array('value' => 'flattermarken',                   'label' => $helper->__('Flattermarken')),
            array('value' => 'gs1-128',                         'label' => $helper->__('GS1-128')),
            array('value' => 'gs1-128composite',                'label' => $helper->__('GS1-128 Composite')),
            array('value' => 'gs1-cc',                          'label' => $helper->__('GS1 Composite 2D Component')),
            array('value' => 'gs1datamatrix',                   'label' => $helper->__('GS1 Data Matrix')),
            array('value' => 'gs1qrcode',                       'label' => $helper->__('GS1 QR Code')),
            array('value' => 'hibccodablockf',                  'label' => $helper->__('HIBC Codablock F')),
            array('value' => 'hibccode128',                     'label' => $helper->__('HIBC Code 128')),
            array('value' => 'hibccode39',                      'label' => $helper->__('HIBC Code 39')),
            array('value' => 'hibcdatamatrix',                  'label' => $helper->__('HIBC Data Matrix')),
            array('value' => 'hibcmicropdf417',                 'label' => $helper->__('HIBC MicroPDF417')),
            array('value' => 'hibcpdf417',                      'label' => $helper->__('HIBC PDF417')),
            array('value' => 'hibcqrcode',                      'label' => $helper->__('HIBC QR Code')),
            array('value' => 'iata2of5',                        'label' => $helper->__('IATA 2 of 5')),
            array('value' => 'identcode',                       'label' => $helper->__('Deutsche Post Identcode')),
            array('value' => 'industrial2of5',                  'label' => $helper->__('Industrial 2 of 5')),
            array('value' => 'interleaved2of5',                 'label' => $helper->__('Interleaved 2 of 5 (ITF)')),
            array('value' => 'isbn',                            'label' => $helper->__('ISBN')),
            array('value' => 'ismn',                            'label' => $helper->__('ISMN')),
            array('value' => 'issn',                            'label' => $helper->__('ISSN')),
            array('value' => 'itf14',                           'label' => $helper->__('ITF-14')),
            array('value' => 'japanpost',                       'label' => $helper->__('Japan Post 4 State Customer Code')),
            array('value' => 'kix',                             'label' => $helper->__('Royal Dutch TPG Post KIX')),
            array('value' => 'leitcode',                        'label' => $helper->__('Deutsche Post Leitcode')),
            array('value' => 'matrix2of5',                      'label' => $helper->__('Matrix 2 of 5')),
            array('value' => 'maxicode',                        'label' => $helper->__('MaxiCode')),
            array('value' => 'micropdf417',                     'label' => $helper->__('MicroPDF417')),
            array('value' => 'microqrcode',                     'label' => $helper->__('Micro QR Code')),
            array('value' => 'msi',                             'label' => $helper->__('MSI Modified Plessey')),
            array('value' => 'onecode',                         'label' => $helper->__('USPS Intelligent Mail')),
            array('value' => 'pdf417',                          'label' => $helper->__('PDF417')),
            array('value' => 'pdf417compact',                   'label' => $helper->__('Compact PDF417')),
            array('value' => 'pharmacode',                      'label' => $helper->__('Pharmaceutical Binary Code')),
            array('value' => 'pharmacode2',                     'label' => $helper->__('Two-track Pharmacode')),
            array('value' => 'planet',                          'label' => $helper->__('USPS PLANET')),
            array('value' => 'plessey',                         'label' => $helper->__('Plessey UK')),
            array('value' => 'posicode',                        'label' => $helper->__('PosiCode')),
            array('value' => 'postnet',                         'label' => $helper->__('USPS POSTNET')),
            array('value' => 'pzn',                             'label' => $helper->__('Pharmazentralnummer (PZN)')),
            array('value' => 'qrcode',                          'label' => $helper->__('QR Code')),
            array('value' => 'rationalizedCodabar',             'label' => $helper->__('Codabar')),
            array('value' => 'raw',                             'label' => $helper->__('Custom 1D symbology')),
            array('value' => 'royalmail',                       'label' => $helper->__('Royal Mail 4 State Customer Code')),
            array('value' => 'sscc18',                          'label' => $helper->__('SSCC-18')),
            array('value' => 'symbol',                          'label' => $helper->__('Miscellaneous symbols')),
            array('value' => 'telepen',                         'label' => $helper->__('Telepen')),
            array('value' => 'telepennumeric',                  'label' => $helper->__('Telepen Numeric')),
            array('value' => 'upca',                            'label' => $helper->__('UPC-A')),
            array('value' => 'upcacomposite',                   'label' => $helper->__('UPC-A Composite')),
            array('value' => 'upce',                            'label' => $helper->__('UPC-E')),
            array('value' => 'upcecomposite',                   'label' => $helper->__('UPC-E Composite'))
        );
    }
}